name: build

on:
  push:
    branches:
      - main
  repository_dispatch:
    types: [doc-rebuild]
  workflow_dispatch:

permissions:
  pages: write
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    needs: render
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
          cache: pip
      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt
      - name: Clone G-ADOPT for API documentation
        uses: actions/checkout@v4
        with:
          repository: g-adopt/g-adopt
          path: g-adopt
      - name: Download rendered notebooks
        uses: dawidd6/action-download-artifact@v6
        with:
          repo: g-adopt/g-adopt
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: render.yml
          name: notebooks
          path: docs/tutorials
      - name: Build site
        run: |
          mkdocs build --clean
      - uses: actions/upload-pages-artifact@v3
        with:
          path: site

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main' || github.event_name == 'repository_dispatch'
    environment:
      name: github-pages
    steps:
      - uses: actions/deploy-pages@v4
